### PR TITLE
Removed moment from bower + version bump

### PR DESCRIPTION
**Pull request by e111077**
vestigial dep removed. Causing issues with modulizer.

### CODE REVIEW

**Comment by e111077** [comment]
image

**Comment by bicknellr** [comment]
This seems fine, "moment" isn't anywhere else in this repo. Were the tests were failing before?

**Comment by e111077** [comment]
No failing tests, but it caused a bunch of warnings in modulizer's build of this element.

**Comment by e111077** [comment]
FF and Polymer 2 seem to be failing on test-fixture?

**Pull request merged**
